
app = "neuro-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/neuro-bot:latest"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

