app = "neuro-bot"

[build]
  # Собираем образ по вашему Dockerfile
  dockerfile = "Dockerfile"

[[services]]
  # Внутренний порт (любое число, бот его не слушает)
  internal_port = 8080
  protocol = "tcp"
  # Отключаем HTTP health-checks и веб-роутинг
  handlers = ["none"]
