name: Fly Deploy

on:
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  FLY_API_TOKEN:   ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions@master

      - name: Flyctl Auth
        run: flyctl auth login --access-token "${{ env.FLY_API_TOKEN }}"

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
