name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # устанавливаем flyctl
      - name: Install flyctl
        uses: superfly/flyctl-actions@v1

      # собственно деплой
      - name: Fly Deploy
        uses: superfly/flyctl-actions@v1
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}



  

